name: Build APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Patch build.gradle.kts
        run: |
          sed -i '/signingConfig = signingConfigs.getByName("debugConfig")/i\
            isCrunchPngs = true\
            isMinifyEnabled = true\
            isShrinkResources = true\
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")' app/build.gradle.kts
          sed -i '/signingConfig = signingConfigs.getByName("debugConfig")/d' app/build.gradle.kts
     
      - name: Ensure proguard-rules.pro exists
        run: touch app/proguard-rules.pro
        
      - name: Build Debug APK
        run: gradle assembleDebug --stacktrace

      - name: Rename APK
        run: cp app/build/outputs/apk/debug/app-debug.apk ${{ github.event.repository.name }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}.apk
